### ISSUE TITLE
[Thunderbird] colored tags are overridden

### ISSUE THREAD

**Issue by ThePhoenixBird** [horst3180/Vertex-theme#49]
I use colored tags to filter my email and easily spot important ones, yet the userChrome.css override any tags colours and always shows white text.

**Comment by ThePhoenixBird** [comment]
The conflicting CSS seems to be:

```css
tree[seltype="cell"] > treechildren::-moz-tree-cell-text,
tree[seltype="text"] > treechildren::-moz-tree-cell-text,
treechildren::-moz-tree-cell-text {
  color: #F3F3F5 !important;
}
```
removed a few selectors

```css
tree[seltype="cell"] > treechildren::-moz-tree-cell-text {
  color: #F3F3F5 !important;
}
```

and now i got my coloured tags back!

hope you can find a better solution of just implement this fix
